<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="3b444e82-6e1e-4572-8a57-3974adbff7bb" name="jkieffer@OMS 2013-03-23 16:17:12" runUser="CLINMIRA\jkieffer" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="1b8b4ad3-d1bf-413d-ba0c-5696d69d5d98">
    <Description>Esta es la configuración de pruebas predeterminada para una ejecución de pruebas local.</Description>
    <Deployment enabled="false" runDeploymentRoot="jkieffer_OMS 2013-03-23 16_17_12" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2013-03-23T16:17:12.3030818-05:00" queuing="2013-03-23T16:17:14.8362267-05:00" start="2013-03-23T16:17:14.9342323-05:00" finish="2013-03-23T16:17:16.2873096-05:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Consulta_Deudor_x_Dni" storage="d:\_karlos\personal\work_upc\repositorio_dsd\wscobranzasoft\fuente_dsd\webapplication1\testwscobranzas\bin\debug\testwscobranzas.dll" id="208c1e3e-2046-696f-3cd5-e79cbc13b10c">
      <Execution id="0a939620-ad2e-44ba-8fac-00d2fb0ca084" />
      <TestMethod codeBase="D:/_Karlos/Personal/Work_UPC/Repositorio_DSD/wscobranzasoft/Fuente_DSD/WebApplication1/TestWScobranzas/bin/Debug/TestWScobranzas.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestWScobranzas.UnitTest1, TestWScobranzas, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Consulta_Deudor_x_Dni" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Resultados que no están en la lista" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="Todos los resultados cargados" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="208c1e3e-2046-696f-3cd5-e79cbc13b10c" executionId="0a939620-ad2e-44ba-8fac-00d2fb0ca084" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="0a939620-ad2e-44ba-8fac-00d2fb0ca084" testId="208c1e3e-2046-696f-3cd5-e79cbc13b10c" testName="Consulta_Deudor_x_Dni" computerName="OMS" duration="00:00:00.5208183" startTime="2013-03-23T16:17:15.2832522-05:00" endTime="2013-03-23T16:17:16.2483074-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="0a939620-ad2e-44ba-8fac-00d2fb0ca084">
      <Output>
        <ErrorInfo>
          <Message>El método de prueba TestWScobranzas.UnitTest1.Consulta_Deudor_x_Dni produjo la excepción: 
System.ServiceModel.FaultException: El servidor no pudo procesar la solicitud debido a un error interno. Para obtener más información acerca del error, active IncludeExceptionDetailInFaults (desde ServiceBehaviorAttribute o desde el comportamiento de configuración de &lt;serviceDebug&gt;) en el servidor para enviar la información de la excepción al cliente, o active la traza según las instrucciones de la documentación de Microsoft .NET Framework 3.0 SDK y consulte los registros de seguimiento del servidor.</Message>
          <StackTrace> 
Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc&amp; rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)
   en TestWScobranzas.ServiceReference1.IService1.get_Deuda_x_Cliente(String str_dni_)
   en TestWScobranzas.ServiceReference1.Service1Client.get_Deuda_x_Cliente(String str_dni_) en D:\_Karlos\Personal\Work_UPC\Repositorio_DSD\wscobranzasoft\Fuente_DSD\WebApplication1\TestWScobranzas\Service References\ServiceReference1\Reference.cs:línea 123
   en TestWScobranzas.UnitTest1.Consulta_Deudor_x_Dni() en D:\_Karlos\Personal\Work_UPC\Repositorio_DSD\wscobranzasoft\Fuente_DSD\WebApplication1\TestWScobranzas\UnitTest1.cs:línea 24
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>